### ISSUE TITLE
AttributeError: 'str' object has no attribute 'size'

### ISSUE THREAD

**Issue by verosol** [bjascob/amrlib#11]
without spacy
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amrlib/models/parse_gsii/bert_utils.py", line 66, in average_pooling
    _, num_total_subwords, hidden_size = encoded_layers.size()
AttributeError: 'str' object has no attribute 'size'

with spacy
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amrlib/models/parse_gsii/bert_utils.py", line 66, in average_pooling
    token_index = torch.arange(num_tokens).view(1, -1, 1).type_as(token_subword_index)
AttributeError: 'str' object has no attribute 'size'

Hi! I am getting this error with both spacy extension and first stog option, troubleshooting does not help much. I understand that  encoded_layers is somehow not an array, but a string somehow, but how come? I just try to execute your examples  (import amrlib
stog = amrlib.load_stog_model()
graphs = stog.parse_sents(['This is a test of the system.', 'This is a second sentence.'])
for graph in graphs:
    print(graph)) and import amrlib
import spacy
amrlib.setup_spacy_extension()
nlp = spacy.load('en_core_web_sm')
doc = nlp('This is a test of the SpaCy extension. The test has multiple sentences.')
graphs = doc._.to_amr()
for graph in graphs:
    print(graph)

**Comment by bjascob** [comment]
This error is related to an update to the tranformers api in the version they just released (4.0.0).  See issue #8 and #9.  Things should now work properly with amrlib 0.2.2 (released last night) and transformers 4.0.0.

**Comment by verosol** [comment]
Thank you for a quick response! It started working in the interactive mode
of the terminal and totally fine, but when I try to call for a .py file
where I want to use it (like : python3 lalala.py) it gives me an error :
Here amr.py only has one line: import amrlib

acBook-Air-user-2:Desktop nikahelicopter$ python3.6 amr.py
Traceback (most recent call last):
  File "amr.py", line 1, in <module>
    import amrlib
  File
"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amrlib/__init__.py",
line 5, in <module>
    from   .models.parse_gsii.inference import Inference as Inference_stog
  File
"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amrlib/models/parse_gsii/inference.py",
line 17, in <module>
    from   ...evaluate.smatch_enhanced import compute_smatch
*  File
"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/amrlib/evaluate/smatch_enhanced.py",
line 6, in <module>*
*    from   amr import AMR*
*ImportError: cannot import name 'AMR'*

Thank you in advance!
Best,
Veronika



пн, 7 дек. 2020 г. в 18:06, Brad Jascob <notifications@github.com>:

**Comment by bjascob** [comment]
The import error is for the amr module is part of the smatch library.  It's in the requirements.txt file.  You need to install that.
