### ISSUE TITLE
Handle graph repair error in deserialize

### ISSUE THREAD

**Issue by flipz357** [bjascob/amrlib#16]
Rarely I get an error here:

https://github.com/bjascob/amrlib/blob/39c8929f35bf354ce0a571997c87eeb9445820c9/amrlib/models/parse_t5/penman_serializer.py#L152

```
    graphs = self.parser.parse_sents(sents)
  File "xxxx/python3.7/site-packages/amrlib/models/parse_t5/inference.py", line 70, in parse_sents
    gstring = PenmanDeSerializer(g).get_graph_string()
  File "xxxx/python3.7/site-packages/amrlib/models/parse_t5/penman_serializer.py", line 104, in __init__
    self.deserialize(gstring)       # sets self.pgraph and self.gstring
  File "xxxx/site-packages/amrlib/models/parse_t5/penman_serializer.py", line 152, in deserialize
    variable = node_stack[-1]
IndexError: list index out of range
```

This error, and possibly similar ones, could maybe be mitigated by replacing
```
        self.deserialize(gstring)       # sets self.pgraph and self.gstring
````
in https://github.com/bjascob/amrlib/blob/39c8929f35bf354ce0a571997c87eeb9445820c9/amrlib/models/parse_t5/penman_serializer.py#L104

with 

```
        try:
            self.deserialize(gstring) # sets self.pgraph and self.gstring
        except:
            self.pgraph, self.gstring = None, None
```
 But there may be a better fix.

**Comment by bjascob** [comment]
Do you happen to have an example sentence that is causing issues?

**Comment by flipz357** [comment]
Unfortunately not right now... I tried to parse like 20k sentences and the program crashed after appr. 4-5 hours. I'll restart the process and report back when I catch the sentence/structure that causes this problem.

**Comment by bjascob** [comment]
If you identify an example I'll see if there's a more robust fix.  However, it's sort of expected that some of these won't deserialize properly and if the deserializer returns None, inference.py will try the next most probable sequence, up to the number of beams (default is 4).  This means that your try/catch is not a bad solution and you should still get back a parse, even if the first attempt fails.  I'll put in a general try/catch around that code, but if you have an example of the issue, I'll try to fix that specific case too.

**Comment by flipz357** [comment]
> This means that your try/catch is not a bad solution and you should still get back a parse, even if the first attempt fails. I'll put in a general try/catch around that code

True, I guess that may be the best solution there is, it's neigh impossible to handle everything that can happen when trying to repair the seq2seq output.

**Comment by bjascob** [comment]
I added the try/catch in commit 7a5c8413538b8283b93a8e374cb7839ab907f1cf.

**Comment by bjascob** [comment]
Crash fix added above.  Closing for now.  Will re-open for changes if specific issues are identified.
