### ISSUE TITLE
Plotting a Graph

### ISSUE THREAD

**Issue by bjascob** [bjascob/amrlib#2]
@myeghaneh
To plot a graph see... see [AMRPlot](https://amrlib.readthedocs.io/en/latest/api_misc/).  There's also a button the UI for this.

Note that this requires graphviz which comes in 2 parts.  The pip install, which is a python wrapper, and the non-python Graphviz install which needs to be done manually.  See the installation instructions on the [pypi page](https://pypi.org/project/graphviz/).

**Comment by myeghaneh** [comment]
Dear Sir

could give me an examplr how can i draw (visualize) the graphs?

considering I have done this part:
```
amrlib.setup_spacy_extension()
nlp = spacy.load("en_core_web_sm")
doc = nlp('This is a test of the SpaCy extension. And when bad luck does
strike and you step into one of the many land mines you have to
painstakingly scrape the remains off your soles.')

# The following are roughly equivalent but demonstrate the different objects.
graphs = doc._.to_amr()
for graph in graphs:
    print(graph)

for span in doc.sents:
    graphs = span._.to_amr()
    print(graphs[0])
```
and it works and it give me the amr. but I can not visualize them as in
your webiste is


Best
Moha

 @myeghaneh

**Comment by bjascob** [comment]
You can follow the command line example for [AMR plotting](https://amrlib.readthedocs.io/en/latest/api_misc/#amr-plotting) or use can use the GUI by running the command [amr_view](https://amrlib.readthedocs.io/en/latest/amr_view/).

For the plotting, make sure you have the graphviz library installed correctly.  See the second bullet under [install the code](https://amrlib.readthedocs.io/en/latest/install/#install-the-code).

**Comment by bjascob** [comment]
It's possible that when you try to plot, the default filename used to hold the temporary plot file won't be accessible on Windows.
I would declare AMRPlot as ...
```
plot = AMRPlot('c:\Temp\amr_graph.gv')
```
or some other location that is writeable.  This should work for now, however I'll look into how to make this more Windows friendly so eventually one doesn't need to provide this.
