### ISSUE TITLE
Request to add more models

### ISSUE THREAD

**Issue by ksmultiacc3** [bjascob/amrlib#20]
This repo seems to have a model with higher smatch, you could please include that in this library as well? I tried and it is breaking the code.-->

Model | Link
-- | --
AMR2.0+BERT+GR=Smatch80.2 | amr2.0.bert.gr.tar.gz
AMR2.0+BERT=Smatch78.7 | amr2.0.bert.tar.gz

https://github.com/jcyk/AMR-gs

The T5 model is too slow to be used.

**Comment by bjascob** [comment]
The parse_gsii is the model from the one from that project.  I doesn't include the graph-recategorization (+GR) so the smatch score is a bit lower.  If you want all the GR stuff, you'll have to use the original project's code.

**Comment by ksmultiacc3** [comment]
:-(
