### ISSUE TITLE
What is the meaning of the alignment result?

### ISSUE THREAD

**Issue by zhaozj89** [bjascob/amrlib#24]
Hi, thanks for this work.
I am trying to understand the alignment result of FAA. For example, 

        # ::status ParsedStatus.OK
        # ::source QA-pairs-first-round_ali-baba-and-forty-thieves-story_1.txt
        # ::nsent 6
        # ::snt building on their father 's business -
        (z0 / build-01
            :location (z1 / business
                          :poss (z2 / person
                                    :ARG0-of (z3 / have-rel-role-91
                                                 :ARG1 (z4 / they)
                                                 :ARG2 (z5 / father)))))

The corresponding alignment result is:

       0-1 1-1.1.r 5-1.1 4-1.1.1.r 2-1.1.1.1.1 3-1.1.1.1.2 

I know the `left` in `left-right` denotes the `left`-th token in the source sentence `:snt`. For `right`, does `1` denote root node? `1.1` denotes the first child of the root node? What is the meaning of `r` in `1.1.r`? Thanks.

**Comment by bjascob** [comment]
The system outputs in the "ISI" alignment format.  There's a copy of the description in this project [here](https://github.com/bjascob/amrlib/blob/master/amrlib/alignments/isi_hand_alignments/AMR-alignment-format.txt) (see `(2)` under Explanation).

Yes,  `n-1` denotes the root node and `n-1.1` is the first sub-amr of the root node.  The suffix `.r` designates the role (aka edge) of a sub-amr.  Looks to me like your example sentence connects like...
```
building   --> (z0 / build-01)
on         --> :location   
business   --> (z1 / business)
's         --> :poss 
their      --> (z4 / they)
father     --> (z5 / father)
```

**Comment by zhaozj89** [comment]
Thanks for the help!
