### ISSUE TITLE
Loading stog_model

### ISSUE THREAD

**Issue by thomashacker** [bjascob/amrlib#25]
Hello 👋
When trying to load the `stog_model` with `load_stog_model` I get a `FileNotFoundError` because the path `"amrlib/data/stog_model"` does not exist.

Looking at the docs I think `stog_model` was renamed to `parse_t5`, correct? There's also no data folder.
Is there a function that downloads the `stog_model` and creates the data folder?

Thanks for the help! ✨

**Comment by bjascob** [comment]
Where did you download the model to?  As per the [install instructions](https://amrlib.readthedocs.io/en/latest/install.html#install-the-models), you either need to rename the downloaded model or set a link to it.  The system looks for the default model at `xxx/amrlib/data/model_stog`.

**Comment by bjascob** [comment]
ToDo: Add verbiage to the error message(s) to indicate that the user must install these separately; that they are not installed by pip.

**Comment by thomashacker** [comment]
Thanks! Sorry, somehow I missed the install instructions... It works perfectly now

**Comment by bjascob** [comment]
Added https://github.com/bjascob/amrlib/commit/1e70741b4ea07ad1b470ff6a241792d49d927d84 to make this clearer in the main README page.

**Comment by BehroozMansouri** [comment]
I have a question regarding loading SPRING model. How can I load this model instead of the default model?

**Comment by bjascob** [comment]
https://amrlib.readthedocs.io/en/latest/api_model/

**Comment by ARQMath** [comment]
I have the following meta file:
{
    "model_type":"stog",
    "version":"0.1.0", 
    "date":"2021-11-25",
    "inference_module":".parse_spring.inference", 
    "inference_class":"Inference",
    "model_fn":"model.pt",
    "kwargs":{}
}

And have downloaded the spring model from "https://github.com/bjascob/amrlib-models" and extracted in ./amrlib/data/model_stog.

I am getting the error: "ModuleNotFoundError: No module named 'amrlib.models.parse_spring'".

Could you please help me with this?

**Comment by bjascob** [comment]
There was a missing "resources" directory for that model and I pushed a quick update to the pypi package (0.7.1) that has this fixed.  Try updating to the latest code and see if that fixes it.  Everything loads fine for me after updating (note that this only impacts the pip installed version.  There are no changes if you just downloaded the code and ran it in place).

On my system I was getting a different error so if you still get the error after updating you'll have to give more details on your specific setup.  The error looks like a path issue that is specific to your system.

If you need additional help, please don't post in a closed issue.  Open a new issue with your specifics.
