### ISSUE TITLE
parse_gtii?

### ISSUE THREAD

**Issue by sderose** [bjascob/amrlib#26]
Hello. I've been trying out amrlib, and have a question about the 2 models, parse_t5 vs. parse_gsii. I easily find the first one, but https://github.com/bjascob/amrlib/blob/master/README.md says there's the second one, too, which I can't find. I also went to the place the page says it's from (https://github.com/jcyk/AMR-gs), and can't find it there either. Any guidance you can provide?

Thanks!

**Comment by bjascob** [comment]
The Read The Docs install page has instructions for installing both parse models (parse_T5 and parse_gsii).  See the install section on the main project page.

**Comment by bjascob** [comment]
Added https://github.com/bjascob/amrlib/commit/1e70741b4ea07ad1b470ff6a241792d49d927d84 to make model download locations clearer in the main README page.
