### ISSUE TITLE
Incorrect PENMAN with multi word expression

### ISSUE THREAD

**Issue by jheinecke** [bjascob/amrlib#27]
Hi,
thanks for this great tool !
I am using it with the T5 parser model, and I stumbled across an error for a sentence with an abbreviation: _Using SEO to Inform Your Website Content Strategy_. Somewhere during the decoding it looks like that SEO is replaced with search engine (optimization) so the created PENMAN graph is syntactically incorrect
(taken from the `parse_sents()` method `amrlib/amrlib/models/parse_t5/inference.py` just before the call to `gstring = PenmanDeSerializer(g).get_graph_string()` (variable `g`in line 70) when the instances not yet given.

https://github.com/bjascob/amrlib/blob/7ddb4dd59f463ffc6e9d659d01b3b36b98d71afe/amrlib/models/parse_t5/inference.py#L69-L71

```
( use-01
    :ARG1 ( search engine    #<--- here is a invalid space
	:name ( name 
		:op1 "SEO" ) )
   :ARG2 ( inform-01 
	:ARG0 use-01
	:ARG1 ( strategy
		 :topic ( content 
			:mod ( website ) )
		 :poss ( you ) ) ) )
```
I guess this can happen with seq2seq models, but is there anything to do to avoid spaces in concept names ?

**Comment by jheinecke** [comment]
Thanks, I didn't see this parameter, I'll try it. 
I just had the idea that if the PenmanSerializer (or something different) in line 70  would be capable to repair "simple" formal errors (like the spaces in concepts or missing final parentheses), could we get even better analyses ? Do you know how often the best scored solution cannot be decoded and therefore skipped ?

**Comment by bjascob** [comment]
Take a look at [PenmanDeserializer](https://github.com/bjascob/amrlib/blob/7ddb4dd59f463ffc6e9d659d01b3b36b98d71afe/amrlib/models/parse_t5/penman_serializer.py#L89).  The code here is trying to reconstruct a properly formed graph even when there are errors in the sequence output.  I think I made the assumption that the output is space tokenized and I don't allow for multi-token node names (I don't think AMR allows for multi-word node names either).  This could probably be modified by adding some logic but you'll need to spend some time to understand how this works as it's a bit complicated already.

Getting the deserializer to work properly was a bit of a chore but the current code seems to work pretty well from a metrics standpoint.  For the current T5 model with PenmanDeserializer, out of the 1898 AMR test graphs, only 1 failed to deserialize properly with a beam size of 1 and all produced results when the beam size was set to 4.
