### ISSUE TITLE
A request for the souce code for training the model

### ISSUE THREAD

**Issue by 14H034160212** [bjascob/amrlib#35]
Hi,

I saw the models for Parse SPRING, Parse T5, Parse GSII, Generate T5wtense, Generate T5. But I did not see the source code for them. Can you post the source code for training those models? Thank you so much.

Merry Christmas.

**Comment by bjascob** [comment]
[Look in the scripts directory](https://github.com/bjascob/amrlib/tree/master/scripts).

**Comment by 14H034160212** [comment]
Thanks a lot!
