### ISSUE TITLE
Missing runs folder

### ISSUE THREAD

**Issue by 14H034160212** [bjascob/amrlib#37]
Hi,

I have one more question related to the `runs` folder. I found `run_tensorboard.sh` under `31_Model_Parse_T5/` and it seems have `runs` folder after training. But I did not find it. Do you know how can I have the `runs` folder? Do I need to set some parameters in `model_parse_t5.json` for that? Thank you so much.
![image](https://user-images.githubusercontent.com/23516191/147573480-f64b84da-c0dd-40c4-9865-52d1ba3ec012.png)

**Comment by bjascob** [comment]
In the current code, nothing gets logged to tensorboard (the `runs` directory) so the `run_tensorboard.sh` script is useless and can be ignored.  There are no parameters you can set to enable this.  It would require some new coding.
