### ISSUE TITLE
Better visualization for *big* AMR graph

### ISSUE THREAD

**Issue by lujiaying** [bjascob/amrlib#4]
The visualization helps a lot. Thanks for releasing this useful tool.

I may have a small suggestion when dealing with big AMR graphs derived from long sentences. 

In https://github.com/bjascob/amrlib/blob/dadb5c4cfba0b4fb0cf4aac9f34ecb28b0086d00/amrlib/graph_processing/amr_plot.py#L12
I was wondering if we could change `format="png"` -> `format="pdf"`, since the image quality of pdf is better than png when zooming the image.

I tried `pdf` on my own mac laptop, it works well. Anyway, it is just my personal preference.

Best,
Jiaying

**Comment by bjascob** [comment]
I'll see what it looks like on Windows and Linux and at least add a parameter so it can be modified easily.

**Comment by bjascob** [comment]
commit d10c97349e5679bc61c2ac092a7ae52af2c89d18 changes the default to 'pdf" and adds a parameter "format" that allows the user to set it.
