### ISSUE TITLE
Tips on Debugging FAA Aligner 

### ISSUE THREAD

**Issue by JosephGatto** [bjascob/amrlib#41]
I have a dataset with hundreds of thousands of parsed AMRs I would like to align. The FAA aligner occasionally fails, most recently with the following error: 

```
[/usr/local/lib/python3.7/dist-packages/amrlib/alignments/faa_aligner/feat2tree.py](https://localhost:8080/#) in __init__(self, id, val, type, feats, is_virtual, pi, pi_edge)
     55         alignsplit = val.split('~')
     56         if len(alignsplit) > 1:
---> 57             self.alignset |= set( int(i) for i in alignsplit[1].split('e.')[1].split(',') )
     58             self.val = alignsplit[0]
     59 

IndexError: list index out of range
```

I have checked that none of the graphs are empty (parser returned nothing). Not sure what else it could be. 

If I dont run the FAA with batches of samples it takes a really long time, wondering if there is anyway to identify the samples breaking this code without aligning them individually.

**Comment by bjascob** [comment]
Unfortunately I didn't write this portion of the code but I'm guessing the issue isn't anything too complicated.  If you have an example sentence / graph that causes the error I can try to fix this and maybe do something like put a try/catch around the problem area so at least it doesn't crash the code.  It shouldn't take too long, I can probably get to later today.

Speed-wise, make sure you're only instantiating the FAA_Aligner() class once as the instantiation is very slow.  You can make multiple calls to ffa_aligner.align_sents() one sentence at a time, though batching will still be faster.

**Comment by bjascob** [comment]
I just pushed a quick fix that will eliminate the error you show above.  If you can identify what sents/graphs are causing you issues I'd still like to see them.  If I know the details of what's going wrong I can probably put in a better fix.  However, at least this bug shouldn't crash the code anymore.
