### ISSUE TITLE
Question for RBW Aligner

### ISSUE THREAD

**Issue by hunter-lee1** [bjascob/amrlib#44]
would you mind describing the format of the alignments more specifically?

# ::alignments 0-1.1.1 1-1.1.2 3-1.1.2.1.2.1 4-1.1.2.1.1.1 5-1.1

**Comment by bjascob** [comment]
It's the standard AMR alignment format from the docs, which is {token number}-{[Gorn Address](https://en.wikipedia.org/wiki/Gorn_address)}
The AMR3 docs have a full description of it [here](https://catalog.ldc.upenn.edu/docs/LDC2020T02/AMR-alignment-format.txt).

**Comment by hunter-lee1** [comment]
Thank u for your relply! It really helps! 

But, is there a good way to get the alignment from the penman_graph (after aligned) ?

**Comment by bjascob** [comment]
I'm not sure what you're asking.  After you align the graph it will have the alignment string in the metadata (as you show above) and the surface alignments (ie... node~e.2) in the graph.  

The penman_graph object comes from the [penman](https://github.com/goodmami/penman) library so you might look in that lib if you need to manipulate that object or extract other information.  If you just want access to the string do something like 
`align_string = penman_graph.metadata['alignments']`

**Comment by hunter-lee1** [comment]
I find it in the Penman Docs. Thank u for ur kind suggestions! It really helps!

`alignment = surface.alignments(penman_graph)`
