### ISSUE TITLE
more AMR-2-text models?

### ISSUE THREAD

**Issue by haixpham** [bjascob/amrlib#48]
Hello,

Thanks for the awesome work! Your library helps simplify the task on AMR a lot!

I wonder, do you have plan to support more AMR2text generative models? I find the T5 model can't handle deeply nested AMR.

**Comment by bjascob** [comment]
I don't have any plans right now for new generate models.  From the scores, the T5generate model should be near SOTA.  What does "can't handle" mean?  Crash, produces poorly formed sentences or is it missing content from the original AMR graph?

**Comment by haixpham** [comment]
In most cases it produces poorly formed sentences from deeply nested AMR graphs.

**Comment by bjascob** [comment]
You'd probably have to figure out some type of "surface planning" model to break the AMR graphs into sub-graphs and determine the correct order for serialization. The current method of serializing based on depth-first recursion is probably not sufficient for the deep graphs.

It's also possible that training a T5-large model would give improved results but you might also need to train with significantly more deep graph AMR data.

Sound like a good research project for someone.
