### ISSUE TITLE
AMR2AMR Variable Alignment

### ISSUE THREAD

**Issue by bjascob** [bjascob/amrlib#5]
@flipz357 suggest the following addition

**AMR2AMR variable alignment**: This could be useful, e.g., for  computing AMR metrics or enabling sentence retrieval via AMR parsed corpora or sentence similarity computation via AMR. It is an NP hard problem but can be implemented  via hill climbing maximizing triple matching. I have been working on this lately, here is a [repo](https://github.com/flipz357/amr-metric-suite) containing AMR metrics (Smatch and S2match) that are based on this alignment. Both alignments should be quite easy to implement in the lib, since it's all native python. (It could be worthwhile, though, to make the alignment faster, e .g., using cython, since it can be very slow for graphs with many variables)

bjascob comment:
It looks like the feature is implemented in the above mentioned repo (and may still be under development).  If other users feel this is required inside of amrlib, feel free to comment.  For now let's keep the functionality separate.  Maybe in a future iteration we can develop a uber alignment suite for amrlib that includes multiple and malleable functionality.

**Comment by flipz357** [comment]
> Maybe in a future iteration we can develop a uber alignment suite for amrlib that includes multiple and malleable functionality.

That's a good suggestion, thanks for your thoughts.

**Comment by bjascob** [comment]
Closed due to inactivity.
