### ISSUE TITLE
STOG: components of name nodes sometimes not as in sentence.

### ISSUE THREAD

**Issue by niccip07** [bjascob/amrlib#57]
Apparently, the compoents of the name node are compared to familiar phrases (I guess) and changed in the graph compared to the sentence.

For instance:
The sentence is: Who is the owner of Universal Studios?
The graph is:
'# ::snt Who is the owner of Universal Studios?
(o / own-01
      :arg0 (a / amr-unknown)
      :arg1 (c / company
            :name (n / name
                  :op1 "Universal"
                  :op2 "Sstudio")))'

"Studios" is changed to "sStudio".

Another example:
The sentence is: When did Dracula's creator die?
The graph is:
(d / die-01
      :ARG1 (p / person
            :ARG0-of (c / create-01
                  :ARG1 (b / book
                        :name (n / name
                              :op1 "drago"))))

How can I prevent the model to change the strings? Especially in the name nodes...

**Comment by niccip07** [comment]
@bjascob Do you have any suggestions to avoid this problem?

**Comment by bjascob** [comment]
Duplicate.  See #54 for answer.
