### ISSUE TITLE
pip install doesn't install amrlib.alignments

### ISSUE THREAD

**Issue by jack-rory-staunton** [bjascob/amrlib#6]
I'm trying to set up amrlib using a pip install. I added a /data folder under amrlib in my conda env and put the models there, and they (seem to) work.

I then follow the instructions 

from amrlib.graph_processing.annotator import add_lemmas
penman_graph = add_lemmas(graph_string, snt_key='snt')

and this works too

but then 

![image](https://user-images.githubusercontent.com/55473618/96920402-1c1b0d80-147b-11eb-8dc7-f575a2e2f5aa.png)

correspondingly, the alignments subfolder is missing from the amrlib package in my conda env. is this a mistake?

thanks in advance 

-Jack

**Comment by jack-rory-staunton** [comment]
also consider including word2number in requirements.txt

**Comment by bjascob** [comment]
Thanks for pointing this out.  
Looks like I was missing an init file and setup wasn't picking up the directory.  The pip install 0.2.1 should now be available and have the fix (including word2number).  Unfortunately I can't test the install right now but I see that the directories are inside the whl file so this should take care of that issue.  Let me know if you run into anything else.

**Comment by jack-rory-staunton** [comment]
thanks
I got it working, and then wanted to try the stog and gtos round-trip. I got it working in jupyterlab initially, but after some other tinkering I now get 

![image](https://user-images.githubusercontent.com/55473618/96937103-6d37fb00-1495-11eb-89ba-5c9a02361242.png)

**Comment by bjascob** [comment]
I haven't seen this circular import error.  I can verify when I start python3, I can import and load the model.
```
>>> import amrlib
>>> gtos = amrlib.load_gtos_model()
````
Not sure what you have going on, unless you have a local file named amrlib.py that it's loading instead of the library.

**Comment by bjascob** [comment]
No additional info reported.  If circular import issues are found, please report this so it can be corrected.
