### ISSUE TITLE
Regarding AMR Parser in German

### ISSUE THREAD

**Issue by acelikyurek** [bjascob/amrlib#69]
Hi,
I want to know that are there any parsers for languages other than English (I am looking for German AMR parser model). Moreover, what will you suggest me for finding a German AMR parser model? Although I checked the internet, I couldn't able to find any model for German version of AMR parser.
Best regards,
K. Atakan Çelikyürek

**Comment by bjascob** [comment]
I'm not familiar with any non-English parsers. The standard AMR 3.0 corpus (which I use here for training the models) is English only. There is AMR training data for Chinese but none for German or any other language.  There is the [4-language translation corpus of AMR 2.0 for the test data](https://catalog.ldc.upenn.edu/LDC2020T07) which includes German. However, this is only the test data so it is probably too small to train a decent parse model.

You would probably be best to use a translation service to translate German to English and use an exiting English model.

**Comment by acelikyurek** [comment]
Thanks for your reply.
Best regards,
Kamil Atakan Çelikyürek

**Comment by nschneid** [comment]
A German AMR dataset was just published: https://aclanthology.org/2024.lrec-main.26/ This can be used to train a German AMR parser.

The translation corpus that @bjascob mentions has been used to develop cross-lingual AMR parsers, which could take a German input sentence and produce an English-style AMR graph.

**Comment by bjascob** [comment]
Just for reference...
The DeAMR corpus is available at https://github.com/chriott/DeAMR.  It's a free corpus and is composed of 400 graphs as described in the above paper.
The [4-language translation of AMR 2.0](https://catalog.ldc.upenn.edu/LDC2020T07) consists of translated test data which is 1,371 sentences per language. There is a fee of $100 for non-LDC members.

**Comment by acelikyurek** [comment]
Hi again,
I was trying to train the model with the set of script named "33_Model_Parse_XFM" with German dataset, cited by @nschneid.
I ended up with too low smatch scores, since the model cannot able to produce too many tokens (like only 2 or 3 tokens per each example).
I think that the reason is the German dataset is too small compared to LDC2020T02 data (~400 data vs. ~60000 data).
Is it truly the case? Note that I also changed the model to multilingual one, i.e., "mbart-large-50".
Moreover, I tried the same set of script on The Little Prince Corpus v3.0 (https://amr.isi.edu/download.html), which has ~1500 data.
Again, I got too low smatch scores.
**Note that I am not fully training them, since I do not have too much computation power (I considered that in one or two epochs later, it should give some meaningful and similar results (like 0.3-0.4 smatch score).)**
Do I miss something?
Best regards,
Kamil Atakan Çelikyürek

**Comment by bjascob** [comment]
The AMR-3 dataset takes about 8 hours using an RTX 3090 to train bart-large. You're going to need similar compute power to train a parse model.  Using all 55K of AMR-3, it takes 1-2 epochs before you start getting reasonable graphs. Before that, they aren't well formed or even recognizable as a graph.  Extrapolating from this, if you only use 1,500 graphs from the Little Prince, I would expected you'd have to do 25-50 epochs before the output started to look reasonable.

I would recommend using the existing training script to fully train mbart-large-50 on the English AMR-3 data as a starting point.  This will teach the LLM to create graphs from sentences.  Once you have it fully trained, switch the 400 German graphs and train for a large number of epochs.

I would also try to find a paper from the group that used the 4-language translation corpus to train a parser and see how they did it.
