### ISSUE TITLE
Ask questions about mapping errors

### ISSUE THREAD

**Issue by Jolin-rgb** [bjascob/amrlib#73]
Do I need to do additional data preprocessing of the text before using the stog parser, I have a lot of mapping errors after my text is processed with the par
![1](https://github.com/user-attachments/assets/5072ed87-1895-4573-8577-d732af535013)
![2](https://github.com/user-attachments/assets/cb853abf-1bb8-4f37-89f9-5b5f2ed90da7)
![3](https://github.com/user-attachments/assets/77938dbd-d821-4a4c-9416-782477b37765)
ser.

**Comment by bjascob** [comment]
It's not uncommon for the parser to log a few warnings. This is the "deserializer" taking the raw output of the language model and re-formatting it to a proper AMR graph.  However, it could be that your incoming sentences are difficult to parse.  **Make sure you're only parsing a single sentence** and not an entire paragraph or block of text all at once. Also make sure you're feeding it proper English sentences and not just data such as a list of items or other non-sentence formatted text.

If you're not doing any of the above and your output looks reasonable, then this is likely just the normal minor formatting errors that the model sometimes produces. If you want to experiment with it more, you can take the AMR 3.0 test set, process it through your code and run SMatch scoring on the results. Scores should be in the low 80s.

**Comment by Jolin-rgb** [comment]
> It's not uncommon for the parser to log a few warnings. This is the "deserializer" taking the raw output of the language model and re-formatting it to a proper AMR graph. However, it could be that your incoming sentences are difficult to parse. **Make sure you're only parsing a single sentence** and not an entire paragraph or block of text all at once. Also make sure you're feeding it proper English sentences and not just data such as a list of items or other non-sentence formatted text.
> 
> If you're not doing any of the above and your output looks reasonable, then this is likely just the normal minor formatting errors that the model sometimes produces. If you want to experiment with it more, you can take the AMR 3.0 test set, process it through your code and run SMatch scoring on the results. Scores should be in the low 80s.

Thank you very much for your reply, it is really very detailed and serious. However, I would like to confirm with you the definition of a single sentence, for example, the sentence I entered into the parser is "The Arlington County Board plans to vote Saturday afternoon on giving Amazon $23 million and other incentives to build a headquarters campus in Crystal City, but only after hearing scores of northern Virginia residents and advocates testify for or against the project." Split by period, this also seems to be a single sentence, but the parser gives the following error:
![1726288938830](https://github.com/user-attachments/assets/7a68cdf5-aa81-4803-a2ef-161d859a9d7b)
However, the following plot results will also be given:
![1726289054609](https://github.com/user-attachments/assets/e6e3ce8b-0a58-4d7d-968f-273f1d3d5a76)
![1726289072688](https://github.com/user-attachments/assets/5e04e98e-2c25-492c-a532-07e4d7a1e37d)
But when the sentence entered into the parser is "The Arlington County Board plans to vote on Saturday afternoon on giving Amazon $23 million and other incentives to build a headquarters campus in Crystal City," or "but only after hearing scores of northern Virginia residents and advocates testify for or against the project." , dividing the previous input into two sentences with a comma，the parser will give a plot result without errors. Is there a clear length limit for the definition of a single sentence or a division with commas and periods as dividers? Or are these three mapping error reminders something that can be ignored? I would like to use the AMR mapping results for downstream tasks, so this is important to me, and I hope to get your answers, thank you very much!

**Comment by bjascob** [comment]
Just do normal sentence splitting at the period. This is normal. If your really worried about performance bart-large will give slightly better results.

**Comment by Jolin-rgb** [comment]
> Just do normal sentence splitting at the period. This is normal. If your really worried about performance bart-large will give slightly better results.

Thank you so much for your answer, it really helped me a lot!! I'd like to ask for another example on how to load the model onto the GPU, I originally loaded it like this but got an error:
![1727108801914](https://github.com/user-attachments/assets/41ca2e79-744b-421b-b94d-4948b7b73bf0)
![1727108559529](https://github.com/user-attachments/assets/1493373a-492f-497b-b753-ef8dc67ae92c)
![1727108700192](https://github.com/user-attachments/assets/3a085647-5579-4617-8133-806e72323bbb)

**Comment by bjascob** [comment]
If you have a GPU the model should load there by default but if you need to specify something different you can just pass in `device` like...
`stog = amrlib.load_stog_model(...., device='cuda:0')`

**Comment by Jolin-rgb** [comment]
> If you have a GPU the model should load there by default but if you need to specify something different you can just pass in `device` like... `stog = amrlib.load_stog_model(...., device='cuda:0')`
Thank you very much for your reply!
